# Generated by Django 4.2.2 on 2025-02-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_token_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
